name: Update NXT Event Data
on:
  schedule:
    - cron: '0 3 * * *' # Daily at 3 a.m.
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Commit placeholder
      run: |
        echo "No external updates needed"