name: Update NXT Event Data
on:
  schedule:
    - cron: '0 3 * * *' # Daily at 3 a.m.
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Update hux
      run: |
        curl -L -o data/hux.json "https://raw.githubusercontent.com/nxtagi/nxtevent/main/data/hux.json"
        
    - name: Update max
      run: |
        curl -L -o data/max.json "https://raw.githubusercontent.com/nxtagi/nxtevent/main/data/max.json"

    - name: Update vel
      run: |
        curl -L -o data/vel.json "https://raw.githubusercontent.com/nxtagi/nxtevent/main/data/vel.json"
        
    - name: Commit changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@users.noreply.github.com"
        git add data/
        git diff --quiet && git diff --staged --quiet || git commit -m "Automatic update: $(date +'%Y-%m-%d %H:%M')"
        git push